[2023-08-01 11:16:38,698: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 11:16:38,698: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 11:59:25,587: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 11:59:25,588: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 12:00:16,839: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 12:00:16,840: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 12:04:20,618: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 12:04:20,628: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 12:04:57,517: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 12:04:57,517: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 12:25:35,646: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 12:25:35,646: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 12:43:20,168: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 12:43:20,169: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 12:44:52,723: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 12:44:52,723: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 12:45:11,314: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 12:45:11,314: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 12:45:16,491: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 12:45:16,491: ERROR: main: DataIngestor.__init__() got an unexpected keyword argument 'config']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 12, in <module>
    data_ingestion.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion = DataIngestor(config=data_ingestion_config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DataIngestor.__init__() got an unexpected keyword argument 'config'
[2023-08-01 13:03:08,897: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 13:03:08,898: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 13:03:17,796: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 13:03:17,796: ERROR: main: DataIngestor.__init__() got an unexpected keyword argument 'config']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 12, in <module>
    data_ingestion.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion = DataIngestor(config=data_ingestion_config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DataIngestor.__init__() got an unexpected keyword argument 'config'
[2023-08-01 13:07:06,955: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 13:07:06,955: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 13:07:15,124: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 13:07:15,124: ERROR: main: DataIngestor.__init__() got an unexpected keyword argument 'config']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 12, in <module>
    data_ingestion.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion = DataIngestor(**data_ingestion_config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DataIngestor.__init__() got an unexpected keyword argument 'config'
[2023-08-01 13:07:58,418: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 13:07:58,418: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 13:08:05,871: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 13:08:05,871: ERROR: main: src.cnnClassifier.components.data_ingestion.DataIngestor() argument after ** must be a mapping, not DataIngestionConfig]
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 12, in <module>
    data_ingestion.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    print(data_ingestion_config,"hihihi")
                     ^^^^^^^^^^^^^^^^^^^^^
TypeError: src.cnnClassifier.components.data_ingestion.DataIngestor() argument after ** must be a mapping, not DataIngestionConfig
[2023-08-01 13:08:46,922: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 13:08:46,922: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 13:08:52,278: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 13:08:52,279: ERROR: main: src.cnnClassifier.components.data_ingestion.DataIngestor() argument after ** must be a mapping, not DataIngestionConfig]
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 12, in <module>
    data_ingestion.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion = DataIngestor(**data_ingestion_config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: src.cnnClassifier.components.data_ingestion.DataIngestor() argument after ** must be a mapping, not DataIngestionConfig
[2023-08-01 13:09:06,535: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 13:09:06,536: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 13:09:12,497: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 13:09:12,497: ERROR: main: src.cnnClassifier.components.data_ingestion.DataIngestor() argument after ** must be a mapping, not DataIngestionConfig]
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 12, in <module>
    data_ingestion.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion = DataIngestor(**data_ingestion_config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: src.cnnClassifier.components.data_ingestion.DataIngestor() argument after ** must be a mapping, not DataIngestionConfig
[2023-08-01 13:10:05,691: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 13:10:05,692: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 13:10:12,390: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 13:10:12,392: ERROR: main: src.cnnClassifier.components.data_ingestion.DataIngestor() argument after ** must be a mapping, not DataIngestionConfig]
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 12, in <module>
    data_ingestion.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion = DataIngestor(data_ingestion_config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: src.cnnClassifier.components.data_ingestion.DataIngestor() argument after ** must be a mapping, not DataIngestionConfig
[2023-08-01 13:11:27,096: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 13:11:27,096: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 13:11:34,107: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 13:11:34,107: ERROR: main: 'DataIngestor' object has no attribute 'load_data']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 12, in <module>
    data_ingestion.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.load_data()
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataIngestor' object has no attribute 'load_data'
[2023-08-01 13:18:32,575: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 13:18:32,576: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 13:18:38,212: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 13:18:38,212: ERROR: main: 'DataIngestor' object has no attribute 'load_data']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 12, in <module>
    data_ingestion.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.load_data()
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataIngestor' object has no attribute 'load_data'
[2023-08-01 13:19:46,803: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 13:19:46,803: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 13:19:54,470: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 13:19:54,470: ERROR: main: 'DataIngestor' object has no attribute 'load_data']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 12, in <module>
    data_ingestion.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.load_and_process_data()
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataIngestor' object has no attribute 'load_data'
[2023-08-01 13:20:31,213: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 13:20:31,214: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 13:20:39,222: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 13:20:39,225: ERROR: main: [Errno 2] No such file or directory: '/kaggle/input/part1-file/blogtext.csv']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 12, in <module>
    data_ingestion.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.load_and_process_data()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\components\data_ingestion.py", line 15, in load_and_process_data
    df = pd.read_csv(self.source_file)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1661, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\common.py", line 859, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/input/part1-file/blogtext.csv'
[2023-08-01 14:36:36,248: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 14:36:36,248: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 14:36:49,104: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 14:36:49,113: ERROR: main: [Errno 2] No such file or directory: 'Chicken-Disease-Classification-Projects-main\\src\\cnnClassifier\\config\\configuration.py']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 12, in <module>
    data_ingestion.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.load_and_process_data()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\components\data_ingestion.py", line 15, in load_and_process_data
    df = pd.read_csv(self.source_file)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1661, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\common.py", line 859, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'Chicken-Disease-Classification-Projects-main\\src\\cnnClassifier\\config\\configuration.py'
[2023-08-01 14:38:41,952: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 14:38:41,953: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 14:38:50,927: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 14:38:50,928: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 14:38:58,447: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 14:38:58,449: ERROR: main: [Errno 2] No such file or directory: 'Chicken-Disease-Classification-Projects-main\\src\\cnnClassifier\\config\\configuration.py\x08logtext.csv']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 12, in <module>
    data_ingestion.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.load_and_process_data()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\components\data_ingestion.py", line 15, in load_and_process_data
    df = pd.read_csv(self.source_file)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1661, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\common.py", line 859, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'Chicken-Disease-Classification-Projects-main\\src\\cnnClassifier\\config\\configuration.py\x08logtext.csv'
[2023-08-01 14:39:13,037: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 14:39:13,040: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 14:39:20,084: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 14:39:20,088: ERROR: main: [Errno 2] No such file or directory: 'Chicken-Disease-Classification-Projects-main\\src\\cnnClassifier\\config\\configuration.py\x08logtext.csv']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 12, in <module>
    data_ingestion.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.load_and_process_data()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\components\data_ingestion.py", line 15, in load_and_process_data
    df = pd.read_csv(self.source_file)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1661, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\common.py", line 859, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'Chicken-Disease-Classification-Projects-main\\src\\cnnClassifier\\config\\configuration.py\x08logtext.csv'
[2023-08-01 14:39:29,018: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 14:39:29,018: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 14:39:35,508: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 14:39:35,511: ERROR: main: [Errno 2] No such file or directory: './blogtext.csv']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 12, in <module>
    data_ingestion.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.load_and_process_data()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\components\data_ingestion.py", line 15, in load_and_process_data
    df = pd.read_csv(self.source_file)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1661, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\common.py", line 859, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './blogtext.csv'
[2023-08-01 14:40:28,447: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 14:40:28,463: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 14:40:32,981: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 14:40:32,984: ERROR: main: [Errno 2] No such file or directory: './blogtext.csv']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 12, in <module>
    data_ingestion.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.load_and_process_data()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\components\data_ingestion.py", line 15, in load_and_process_data
    df = pd.read_csv(self.source_file)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1661, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\common.py", line 859, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './blogtext.csv'
[2023-08-01 14:41:33,597: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 14:41:33,598: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 14:41:38,974: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 14:41:38,976: ERROR: main: [Errno 2] No such file or directory: './blogtext.csv']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 12, in <module>
    data_ingestion.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.load_and_process_data()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\components\data_ingestion.py", line 15, in load_and_process_data
    df = pd.read_csv(self.source_file)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1661, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\common.py", line 859, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './blogtext.csv'
[2023-08-01 14:41:49,473: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 14:41:49,473: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 14:41:54,496: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 14:41:54,497: ERROR: main: [Errno 22] Invalid argument: 'C:\\work\\MLOPS\\Chicken-Disease-Classification-Projects-main\\Chicken-Disease-Classification-Projects-main\\src\\cnnClassifier\\config\x08logtext.csv']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 12, in <module>
    data_ingestion.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.load_and_process_data()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\components\data_ingestion.py", line 15, in load_and_process_data
    df = pd.read_csv(self.source_file)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1661, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\common.py", line 859, in get_handle
    handle = open(
             ^^^^^
OSError: [Errno 22] Invalid argument: 'C:\\work\\MLOPS\\Chicken-Disease-Classification-Projects-main\\Chicken-Disease-Classification-Projects-main\\src\\cnnClassifier\\config\x08logtext.csv'
[2023-08-01 14:42:26,691: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 14:42:26,691: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 14:42:31,674: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 14:42:31,676: ERROR: main: [Errno 22] Invalid argument: 'C:\\work\\MLOPS\\Chicken-Disease-Classification-Projects-main\\Chicken-Disease-Classification-Projects-main\\src\\cnnClassifier\\config\x08logtext.csv']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 12, in <module>
    data_ingestion.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.load_and_process_data()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\components\data_ingestion.py", line 15, in load_and_process_data
    df = pd.read_csv(self.source_file)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1661, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\common.py", line 859, in get_handle
    handle = open(
             ^^^^^
OSError: [Errno 22] Invalid argument: 'C:\\work\\MLOPS\\Chicken-Disease-Classification-Projects-main\\Chicken-Disease-Classification-Projects-main\\src\\cnnClassifier\\config\x08logtext.csv'
[2023-08-01 14:43:39,090: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 14:43:39,091: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 14:43:44,148: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 14:43:44,149: ERROR: main: [Errno 22] Invalid argument: 'C:\\work\\MLOPS\\Chicken-Disease-Classification-Projects-main\\Chicken-Disease-Classification-Projects-main\\src\\cnnClassifier\\config\x08logtext.csv']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 12, in <module>
    data_ingestion.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.load_and_process_data()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\components\data_ingestion.py", line 15, in load_and_process_data
    df = pd.read_csv(self.source_file)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1661, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\common.py", line 859, in get_handle
    handle = open(
             ^^^^^
OSError: [Errno 22] Invalid argument: 'C:\\work\\MLOPS\\Chicken-Disease-Classification-Projects-main\\Chicken-Disease-Classification-Projects-main\\src\\cnnClassifier\\config\x08logtext.csv'
[2023-08-01 14:44:08,550: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 14:44:08,550: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 14:44:13,572: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 14:44:58,009: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-01 14:44:58,009: INFO: main: *******************]
[2023-08-01 14:44:58,009: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-01 14:44:58,017: ERROR: main: 'ConfigurationManager' object has no attribute 'get_prepare_base_model_config']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 24, in <module>
    prepare_base_model.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 14, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'get_prepare_base_model_config'
[2023-08-01 14:59:33,332: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 14:59:33,332: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 14:59:39,947: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 14:59:39,947: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 14:59:50,273: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 15:00:31,401: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-01 15:00:31,410: INFO: main: *******************]
[2023-08-01 15:00:31,411: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-01 15:00:31,411: ERROR: main: BaseModelPreparer.__init__() got an unexpected keyword argument 'config']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 24, in <module>
    prepare_base_model.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model = BaseModelPreparer(config=prepare_base_model_config)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseModelPreparer.__init__() got an unexpected keyword argument 'config'
[2023-08-01 15:14:43,790: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 15:14:43,791: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 15:14:51,595: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 15:15:47,967: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-01 15:15:47,970: INFO: main: *******************]
[2023-08-01 15:15:47,970: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-01 15:15:47,974: ERROR: main: BaseModelPreparer.__init__() got an unexpected keyword argument 'config']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 24, in <module>
    prepare_base_model.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model = BaseModelPreparer(config=prepare_base_model_config)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseModelPreparer.__init__() got an unexpected keyword argument 'config'
[2023-08-01 15:19:47,535: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 15:19:47,535: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 15:20:01,820: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 15:21:00,732: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-01 15:21:00,732: INFO: main: *******************]
[2023-08-01 15:21:00,732: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-01 15:21:00,739: ERROR: main: PrepareBaseModelTrainingPipeline.__init__() missing 4 required positional arguments: 'train_inputs', 'val_inputs', 'train_labels', and 'val_labels']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 23, in <module>
    prepare_base_model = PrepareBaseModelTrainingPipeline()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PrepareBaseModelTrainingPipeline.__init__() missing 4 required positional arguments: 'train_inputs', 'val_inputs', 'train_labels', and 'val_labels'
[2023-08-01 15:23:11,360: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 15:23:11,360: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 15:23:19,608: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 15:23:21,563: ERROR: main: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.]
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 12, in <module>
    logger.info(f">>>>>> stage {STAGE_NAME} started <<<<<<")
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.load_and_process_data()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\components\data_ingestion.py", line 15, in load_and_process_data
    df = pd.read_csv(self.source_file)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 583, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1704, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sumeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas\_libs\parsers.pyx", line 812, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas\_libs\parsers.pyx", line 873, in pandas._libs.parsers.TextReader._read_rows
  File "pandas\_libs\parsers.pyx", line 848, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas\_libs\parsers.pyx", line 859, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "pandas\_libs\parsers.pyx", line 2025, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.
[2023-08-01 15:23:24,728: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 15:23:24,728: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 15:23:29,932: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 15:24:12,722: ERROR: main: cannot unpack non-iterable NoneType object]
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 14, in <module>
    train_inputs, val_inputs, train_labels, val_labels = data_ingestion.main()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
[2023-08-01 15:25:34,007: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 15:25:34,007: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 15:25:39,470: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 15:26:20,227: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-01 15:26:20,243: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-01 15:26:20,246: ERROR: main: PrepareBaseModelTrainingPipeline.__init__() takes 5 positional arguments but 6 were given]
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 22, in <module>
    prepare_base_model = PrepareBaseModelTrainingPipeline(base_model_config, train_inputs, val_inputs, train_labels, val_labels)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PrepareBaseModelTrainingPipeline.__init__() takes 5 positional arguments but 6 were given
[2023-08-01 15:27:20,527: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 15:27:20,527: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 15:27:31,254: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 15:27:31,254: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 15:27:36,161: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 15:28:17,297: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-01 15:28:17,297: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-01 15:28:17,313: ERROR: main: 'ConfigurationManager' object has no attribute 'get_prepare_base_model_config']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 23, in <module>
    model = prepare_base_model.main()
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 19, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'get_prepare_base_model_config'
[2023-08-01 15:29:00,895: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 15:29:00,895: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 15:29:08,089: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 15:29:50,787: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-01 15:29:50,787: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-01 15:29:50,793: ERROR: main: 'ConfigurationManager' object has no attribute 'get_prepare_base_model_config']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 23, in <module>
    model = prepare_base_model.main()
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 19, in main
    prepare_base_model_config = config.get_base_model_preparation_config()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'get_prepare_base_model_config'
[2023-08-01 15:30:31,317: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 15:30:31,317: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 15:30:36,847: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 15:31:16,388: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-01 15:31:16,388: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-01 15:31:16,396: ERROR: main: src.cnnClassifier.components.prepare_base_model.BaseModelPreparer() argument after ** must be a mapping, not BaseModelPreparationConfig]
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 23, in <module>
    model = prepare_base_model.main()
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 21, in main
    base_model_preparer = BaseModelPreparer(**prepare_base_model_config)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: src.cnnClassifier.components.prepare_base_model.BaseModelPreparer() argument after ** must be a mapping, not BaseModelPreparationConfig
[2023-08-01 15:36:21,056: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 15:36:21,056: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 15:36:28,162: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 15:37:07,952: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-01 15:37:07,955: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-01 15:37:07,957: ERROR: main: 'ConfigurationManager' object has no attribute 'get_prepare_base_model_config']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 23, in <module>
    model = prepare_base_model.main()
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 19, in main
    prepare_base_model_config = config.get_base_model_preparation_config().to_dict()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'get_prepare_base_model_config'
[2023-08-01 15:37:22,769: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 15:37:22,769: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 15:37:28,566: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 15:38:08,972: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-01 15:38:08,972: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-01 15:38:08,984: ERROR: main: 'BaseModelPreparationConfig' object has no attribute 'to_dict']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 23, in <module>
    model = prepare_base_model.main()
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 19, in main
    prepare_base_model_config = config.get_base_model_preparation_config().to_dict()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BaseModelPreparationConfig' object has no attribute 'to_dict'
[2023-08-01 15:40:44,816: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 15:40:44,816: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 15:40:50,422: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 15:41:41,215: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-01 15:41:41,215: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-01 15:41:41,215: ERROR: main: 'BaseModelPreparationConfig' object has no attribute 'to_dict']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 23, in <module>
    model = prepare_base_model.main()
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 19, in main
    prepare_base_model_config = config.get_base_model_preparation_config().to_dict()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BaseModelPreparationConfig' object has no attribute 'to_dict'
[2023-08-01 15:42:39,271: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 15:42:39,286: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 15:42:44,490: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 15:43:28,187: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-01 15:43:28,187: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-01 15:43:50,272: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-08-01 15:43:50,272: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-08-01 15:43:50,272: ERROR: main: ModelTrainingPipeline.__init__() takes 1 positional argument but 6 were given]
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 29, in <module>
    model_trainer = ModelTrainingPipeline(model, train_inputs, val_inputs, train_labels, val_labels)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelTrainingPipeline.__init__() takes 1 positional argument but 6 were given
[2023-08-01 15:46:22,518: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 15:46:22,518: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 15:46:30,168: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 15:47:11,014: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-01 15:47:11,014: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-01 16:39:42,923: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 16:39:42,923: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 16:39:49,462: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 16:40:46,428: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-01 16:40:46,477: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-01 16:40:58,053: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-08-01 16:40:58,053: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-08-01 16:40:58,053: ERROR: main: ModelTrainingPipeline.__init__() takes 1 positional argument but 6 were given]
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 29, in <module>
    model_trainer = ModelTrainingPipeline(model, train_inputs, val_inputs, train_labels, val_labels)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelTrainingPipeline.__init__() takes 1 positional argument but 6 were given
[2023-08-01 16:43:36,940: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 16:43:36,940: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 16:43:43,096: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 16:44:49,686: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-01 16:44:49,686: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-01 16:44:55,677: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-08-01 16:44:55,678: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-08-01 16:44:55,678: ERROR: main: 'ConfigurationManager' object has no attribute 'get_prepare_callback_config']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 30, in <module>
    model_trainer.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_03_training.py", line 19, in main
    prepare_callbacks_config = config.get_prepare_callback_config()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'get_prepare_callback_config'
[2023-08-01 16:45:32,864: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 16:45:32,864: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 16:45:38,002: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 16:46:19,342: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-01 16:46:19,342: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-01 16:46:25,747: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-08-01 16:46:25,747: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-08-01 16:46:25,747: ERROR: main: CallbacksPreparer.__init__() got an unexpected keyword argument 'config']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 30, in <module>
    model_trainer.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_03_training.py", line 20, in main
    prepare_callbacks = CallbacksPreparer(config=prepare_callbacks_config)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CallbacksPreparer.__init__() got an unexpected keyword argument 'config'
[2023-08-01 16:57:12,646: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 16:57:12,646: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 16:57:18,369: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 16:57:53,855: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-01 16:57:53,855: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-01 16:58:00,045: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-08-01 16:58:00,045: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-08-01 16:58:00,054: ERROR: main: src.cnnClassifier.components.prepare_callbacks.CallbacksPreparer() argument after ** must be a mapping, not CallbacksPreparationConfig]
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 30, in <module>
    model_trainer.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_03_training.py", line 20, in main
    prepare_callbacks = CallbacksPreparer(**prepare_callbacks_config)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: src.cnnClassifier.components.prepare_callbacks.CallbacksPreparer() argument after ** must be a mapping, not CallbacksPreparationConfig
[2023-08-01 16:59:05,717: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 16:59:05,717: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 16:59:12,056: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 16:59:47,942: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-01 16:59:47,942: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-01 16:59:54,149: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-08-01 16:59:54,149: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-08-01 16:59:54,161: ERROR: main: Trainer.__init__() got an unexpected keyword argument 'config']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 30, in <module>
    model_trainer.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_03_training.py", line 24, in main
    training = Trainer(config=training_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Trainer.__init__() got an unexpected keyword argument 'config'
[2023-08-01 17:01:17,143: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 17:01:17,143: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 17:01:21,947: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 17:02:15,812: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-01 17:02:15,812: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-01 17:02:29,211: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-08-01 17:02:29,211: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-08-01 17:02:29,211: ERROR: main: 'TrainingConfig' object has no attribute 'base_model_name']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 30, in <module>
    model_trainer.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_03_training.py", line 23, in main
    training_config = config.get_training_config().to_dict()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\config\configuration.py", line 40, in to_dict
    'base_model_name': self.base_model_name,
                       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TrainingConfig' object has no attribute 'base_model_name'
[2023-08-01 17:05:20,315: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 17:05:20,315: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 17:05:26,188: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 17:06:00,899: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-01 17:06:00,899: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-01 17:06:06,623: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-08-01 17:06:06,623: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-08-01 17:06:06,630: ERROR: main: 'TrainingConfig' object has no attribute 'base_model_name']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 30, in <module>
    model_trainer.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_03_training.py", line 23, in main
    training_config = config.get_training_config().to_dict()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\config\configuration.py", line 40, in to_dict
    def to_dict(self):
                       
AttributeError: 'TrainingConfig' object has no attribute 'base_model_name'
[2023-08-01 17:07:35,213: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 17:07:35,213: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 17:07:41,590: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 17:08:16,133: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-01 17:08:16,133: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-01 17:08:21,965: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-08-01 17:08:21,965: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-08-01 17:08:21,965: ERROR: main: TrainingConfig.__init__() missing 2 required positional arguments: 'base_model_name' and 'intents']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 30, in <module>
    model_trainer.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_03_training.py", line 23, in main
    training_config = config.get_training_config().to_dict()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\config\configuration.py", line 86, in get_training_config
    return TrainingConfig(epochs)
           ^^^^^^^^^^^^^^^^^^^^^^
TypeError: TrainingConfig.__init__() missing 2 required positional arguments: 'base_model_name' and 'intents'
[2023-08-01 17:10:03,799: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 17:10:03,799: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 17:10:09,047: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 17:10:54,153: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-01 17:10:54,153: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-01 17:10:59,979: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-08-01 17:10:59,979: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-08-01 17:10:59,979: ERROR: main: 'ConfigurationManager' object has no attribute 'config']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 30, in <module>
    model_trainer.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_03_training.py", line 23, in main
    training_config = config.get_training_config().to_dict()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\config\configuration.py", line 84, in get_training_config
    epochs = self.config['training']['epochs']
             ^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'config'
[2023-08-01 17:12:24,745: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 17:12:24,745: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 17:12:30,652: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 17:12:30,653: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 17:12:35,363: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 17:12:35,363: ERROR: main: 'ConfigurationManager' object has no attribute 'load_config']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 14, in <module>
    train_inputs, val_inputs, train_labels, val_labels = data_ingestion.main()
                                                         ^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 13, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\config\configuration.py", line 47, in __init__
    self.config = self.load_config()  # or however you're loading the config data
                  ^^^^^^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'load_config'
[2023-08-01 17:19:41,592: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 17:19:41,592: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 17:19:49,387: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 17:20:26,296: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-01 17:20:26,296: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-01 17:20:35,081: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-08-01 17:20:35,082: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-08-01 17:20:35,083: ERROR: main: 'ConfigurationManager' object has no attribute 'config']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 30, in <module>
    model_trainer.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_03_training.py", line 23, in main
    training_config = config.get_training_config().to_dict()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\config\configuration.py", line 103, in get_training_config
    epochs = self.config['training']['epochs']
             ^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'config'
[2023-08-01 17:22:46,392: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-01 17:22:46,392: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-08-01 17:22:51,106: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-01 17:23:25,748: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-01 17:23:25,748: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-01 17:23:32,101: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-08-01 17:23:32,101: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-08-01 17:23:32,101: ERROR: main: Trainer.__init__() got an unexpected keyword argument 'base_model_name']
Traceback (most recent call last):
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\main.py", line 30, in <module>
    model_trainer.main()
  File "C:\work\MLOPS\Chicken-Disease-Classification-Projects-main\Chicken-Disease-Classification-Projects-main\src\cnnClassifier\pipeline\stage_03_training.py", line 24, in main
    training = Trainer(**training_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Trainer.__init__() got an unexpected keyword argument 'base_model_name'
